### ISSUE TITLE
Timeout crash while waiting for a command

### ISSUE THREAD

**Issue by gordonwatts** [LHCAtlas/AtlasSSH#236]
System.TimeoutException occurred
      HResult=0x80131505
      Message=Waiting for 'find /LLPData/GRIDDS/user.gwatts.00296939.physics_Main.DAOD_EXOT15.f685_m1576_p2950.DiVertAnalysis_v201_7EB0B08D_70111BBF_hist -print' back from host and it was not seen inside of 10 seconds. - occured while executing command find /LLPData/GRIDDS/user.gwatts.00296939.physics_Main.DAOD_EXOT15.f685_m1576_p2950.DiVertAnalysis_v201_7EB0B08D_70111BBF_hist -print. Last text we saw was '' - While executing command find /LLPData/GRIDDS/user.gwatts.00296939.physics_Main.DAOD_EXOT15.f685_m1576_p2950.DiVertAnalysis_v201_7EB0B08D_70111BBF_hist -print.
      Source=<Cannot evaluate the exception source>
      StackTrace:
       at AtlasSSH.AtlasCommands.ExecuteLinuxCommand(ISSHConnection connection, String command, Action`1 processLine, Func`1 failNow, Boolean dumpOnly, Int32 secondsTimeout, Boolean refreshTimeout, Dictionary`2 seeAndRespond)
       at AtlasWorkFlows.Locations.PlaceLinuxRemote.<>c__DisplayClass33_0.<GetAbosluteLinuxFilePaths>b__0()
       at AtlasWorkFlows.Utils.InMemoryObjectCache`1.GetOrCalc(String key, Func`1 calculate)
       at AtlasWorkFlows.Locations.PlaceLinuxRemote.GetAbosluteLinuxFilePaths(String dsname, Action`1 statusUpdate, Func`1 failNow)
       at AtlasWorkFlows.Locations.PlaceLinuxRemote.HasFile(Uri u, Action`1 statusUpdate, Func`1 failNow)
       at AtlasWorkFlows.DatasetManager.<>c__DisplayClass5_1.<ListOfPlacesHoldingAllFiles>b__2(Uri f)
       at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
       at AtlasWorkFlows.DatasetManager.<>c__DisplayClass5_0.<ListOfPlacesHoldingAllFiles>b__1(IPlace p)
       at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
       at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at AtlasWorkFlows.DatasetManager.ListOfPlacesHoldingAllFiles(IEnumerable`1 dsfiles, Int32 maxDataTier)
       at libDataAccess.GRIDJobs.FindJobUris(String jobName, Int32 jobVersionNumber, String dsname, Int32 nFiles, Action`1 statusUpdate, String[] avoidPlaces) in C:\Users\gordonwatts\Documents\Code\calratio\JetCutStudies\libDataAccess\GRIDJobs.cs:line 106
       at libDataAccess.Files.GetFileList(String dsname, String[] avoidPlaces) in C:\Users\gordonwatts\Documents\Code\calratio\JetCutStudies\libDataAccess\Files.cs:line 82
       at libDataAccess.Files.<>c__DisplayClass11_0.<SamplesAsSingleQueriable>b__0(SampleMetaData s) in C:\Users\gordonwatts\Documents\Code\calratio\JetCutStudies\libDataAccess\Files.cs:line 167
       at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at libDataAccess.Files.SamplesAsSingleQueriable(IEnumerable`1 source, String[] avoidPlaces) in C:\Users\gordonwatts\Documents\Code\calratio\JetCutStudies\libDataAccess\Files.cs:line 166
       at libDataAccess.Utils.BIBSamples.GetBIBSamples(Int32 requestedNumberOfEvents, DataEpoc epoc, Double pTCut, String[] avoidPlaces) in C:\Users\gordonwatts\Documents\Code\calratio\JetCutStudies\libDataAccess\Utils\BIBSamples.cs:line 74
       at JetMVAClassifierTraining.Program.Main(String[] args) in C:\Users\gordonwatts\Documents\Code\calratio\JetCutStudies\JetMVAClassifierTraining\Program.cs:line 218
    
    Inner Exception 1:
    TimeoutException: Waiting for 'find /LLPData/GRIDDS/user.gwatts.00296939.physics_Main.DAOD_EXOT15.f685_m1576_p2950.DiVertAnalysis_v201_7EB0B08D_70111BBF_hist -print' back from host and it was not seen inside of 10 seconds. - occured while executing command find /LLPData/GRIDDS/user.gwatts.00296939.physics_Main.DAOD_EXOT15.f685_m1576_p2950.DiVertAnalysis_v201_7EB0B08D_70111BBF_hist -print. Last text we saw was ''
    
    Inner Exception 2:
    TimeoutException: Waiting for 'find /LLPData/GRIDDS/user.gwatts.00296939.physics_Main.DAOD_EXOT15.f685_m1576_p2950.DiVertAnalysis_v201_7EB0B08D_70111BBF_hist -print' back from host and it was not seen inside of 10 seconds.

**Comment by gordonwatts** [comment]
Two things:

- Make sure this timeout is fixed with a broken connection fix
- Increase the 10 second timeout to 20 seconds - sometimes these systems get loaded down.
